### ISSUE TITLE
Website go live checklist

### ISSUE THREAD

**Issue by libcce** [libcce/gofairna#1]
- [ ] Review/update logo(s)
- [x] Name - GO FAIR North America (Network)
- [ ] Brief description of relationship to GO FAIR
- [x] Update teaser in header (current Advancing FAIR in North America)
- [ ] Determine footer information/links
- [ ] Determine header image/color
- [x] Buy domain name - go-fair-na
- [ ] GitHub organization - sdsc
- [ ] Review Code of Conduct (https://github.com/libcce/gofairna/blob/master/conduct.md)
- [ ] Plan events page (virtual, in-person, calendar, archive) on network (code of conduct), training, assessment tools, lesson sprint, fair in ai… disciplines
- [ ] Create Twitter handle/hashtag - GOFAIRNA
- [ ] Review initial blog post
- [ ] Plan/schedule subsequent blog posts
- [ ] Google analytics (overall analytics plan)
- [ ] FAIR Principles page (brief description, examples, possibly from Top 10 FAIR)
- [ ] Review About page
- [ ] Update Workshop page w/ event name & location, agenda table, funders/sponsors, organizers
- [ ]  Review Connect page

**Comment by libcce** [comment]
From meeting on 2020-03-12 w/ @SuperChristineK and Melissa Cragin:

Decisions:
- Domain - gofair.us (points to gofair.org for the moment)
- Go FAIR US for now, reach out to others in North America to see if we can be more inclusive.
- Teaser - Advancing FAIR in the US (or United States)

Looking into:
- Use the Go FAIR website design template
- Check whether SDSC can create a GitHub repo in their organization
- Create blog post from report
